version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto1.8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn war:war
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/EggHeads-Frontend_p2-0.1.war